name: CI and Publish
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

  publish:
    name: Pack and Publish to GitHub Packages
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Pack library
        run: >-
          dotnet pack .\Polly.Contrib.DuplicateRequestCollapser\Polly.Contrib.DuplicateRequestCollapser.csproj
          --configuration Release
          --no-build
          --include-symbols
          --output .\out

      - name: Publish to GitHub Packages
        env:
          NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: >-
          dotnet nuget push .\out\*.nupkg
          --api-key $env:NUGET_API_KEY
          --source "https://nuget.pkg.github.com/$env:OWNER/index.json"
          --skip-duplicate

      - name: Publish symbols to GitHub Packages (snupkg)
        env:
          NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: >-
          dotnet nuget push .\out\*.snupkg
          --api-key $env:NUGET_API_KEY
          --source "https://nuget.pkg.github.com/$env:OWNER/index.json"
          --skip-duplicate
